#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create swh table."""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed8813bfcb2b"
down_revision = "6cfb865654d2"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swh_deposit",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column(
            "object_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("swhid", sa.String(length=255), nullable=True),
        sa.Column("swh_deposit_id", sa.String(), nullable=True),
        sa.Column("status", sa.CHAR(length=1), nullable=False),
        sa.PrimaryKeyConstraint("object_uuid", name=op.f("pk_swh_deposit")),
    )
    op.create_index(
        op.f("ix_swh_deposit_status"), "swh_deposit", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swh_deposit_status"), table_name="swh_deposit")
    op.drop_table("swh_deposit")
    # ### end Alembic commands ###
